// <auto-generated />
using System;
using EFCoreTraining.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreTraining.Migrations
{
    [DbContext(typeof(AddDbContext))]
    [Migration("20260218091553_ConsoleMenu")]
    partial class ConsoleMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("CoursesCourseId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("Student Courses", (string)null);
                });

            modelBuilder.Entity("EFCoreTraining.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("TrainerId");

                    b.ToTable("batches");
                });

            modelBuilder.Entity("EFCoreTraining.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("Fees")
                        .HasColumnType("Decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            CourseId = 101,
                            DurationInMonths = 4,
                            Fees = 5000m,
                            Title = ".NET"
                        },
                        new
                        {
                            CourseId = 102,
                            DurationInMonths = 2,
                            Fees = 3000m,
                            Title = "C#"
                        });
                });

            modelBuilder.Entity("EFCoreTraining.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CreatedDate = new DateOnly(2026, 2, 18),
                            Email = "het@gmail.com",
                            Name = "Het Patel"
                        },
                        new
                        {
                            StudentId = 2,
                            CreatedDate = new DateOnly(2026, 2, 18),
                            Email = "niken@gmail.com",
                            Name = "Niken Patel"
                        },
                        new
                        {
                            StudentId = 3,
                            CreatedDate = new DateOnly(2026, 2, 18),
                            Email = "megh@gmail.com",
                            Name = "Megh Mewada"
                        });
                });

            modelBuilder.Entity("EFCoreTraining.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerId");

                    b.ToTable("trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = 1,
                            ExperienceYears = 5,
                            Name = "Jaydip Mer"
                        },
                        new
                        {
                            TrainerId = 2,
                            ExperienceYears = 5,
                            Name = "Vivek Vaghasiya"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("EFCoreTraining.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreTraining.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreTraining.Models.Batch", b =>
                {
                    b.HasOne("EFCoreTraining.Models.Course", "Course")
                        .WithMany("Batch")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreTraining.Models.Trainer", "trainer")
                        .WithMany("Batch")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("trainer");
                });

            modelBuilder.Entity("EFCoreTraining.Models.Course", b =>
                {
                    b.Navigation("Batch");
                });

            modelBuilder.Entity("EFCoreTraining.Models.Trainer", b =>
                {
                    b.Navigation("Batch");
                });
#pragma warning restore 612, 618
        }
    }
}
