// <auto-generated />
using System;
using CorporateTrainingManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CorporateTrainingManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222120718_InitialFunctionRequirements")]
    partial class InitialFunctionRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique()
                        .HasFilter("[DepartmentName] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentLocation = "Ahmedabad",
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentLocation = "mumbai",
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentLocation = "bangaluru",
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentLocation = "bangaluru",
                            DepartmentName = "Networking"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentLocation = "Ahmedabad",
                            DepartmentName = "QA"
                        });
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeEmail")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            EmployeeEmail = "het@mail",
                            EmployeeName = "het"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            EmployeeEmail = "niken@mail",
                            EmployeeName = "niken"
                        });
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int>("PerformanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrProgramId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("TrProgramId");

                    b.HasIndex("EmployeeId", "TrProgramId")
                        .IsUnique();

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasCheckConstraint("CK_MAX_SCORE < 100", "[PerformanceScore]<100");
                        });
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<int>("ExpertiseLevel")
                        .HasColumnType("int");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = 1,
                            ExpertiseLevel = 5,
                            TrainerName = "rahul"
                        },
                        new
                        {
                            TrainerId = 2,
                            ExpertiseLevel = 5,
                            TrainerName = "mehul"
                        });
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.TrainingProgram", b =>
                {
                    b.Property<int>("TrProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrProgramId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("TrProgramId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingPrograms");

                    b.HasData(
                        new
                        {
                            TrProgramId = 1,
                            Duration = 5,
                            StartDate = new DateOnly(1, 1, 1),
                            Title = "Public Speaking",
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Employee", b =>
                {
                    b.HasOne("CorporateTrainingManagementSystem.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Enrollment", b =>
                {
                    b.HasOne("CorporateTrainingManagementSystem.Model.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CorporateTrainingManagementSystem.Model.TrainingProgram", "TrainingProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.TrainingProgram", b =>
                {
                    b.HasOne("CorporateTrainingManagementSystem.Model.Trainer", "Trainer")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Employee", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.Trainer", b =>
                {
                    b.Navigation("TrainingPrograms");
                });

            modelBuilder.Entity("CorporateTrainingManagementSystem.Model.TrainingProgram", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
